## Swagger
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

## H2 DataSource
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password

## JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true

## Goflightlabs
url:
  access-key:
  base: https://app.goflightlabs.com

## Server
server:
  servlet:
    context-path: /air-ticket-booking

## Security secret key
jwt:
  secret:
    key: 7639792442264528482B4D6251655468576D5A7134743777217A25432A462D4A